// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVywqCqXb8pdR5qDs9wIZvKSPoYgR873Y',
    appId: '1:687935619017:web:d342f61ea84cb16c80f218',
    messagingSenderId: '687935619017',
    projectId: 'writing-learner-app',
    authDomain: 'writing-learner-app.firebaseapp.com',
    storageBucket: 'writing-learner-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-N0vzHRzyPiUOEo3iOpcPGumC2gPqwM',
    appId: '1:687935619017:android:37484600fbef804a80f218',
    messagingSenderId: '687935619017',
    projectId: 'writing-learner-app',
    storageBucket: 'writing-learner-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFxn0YN57PQFHv5pcnmJqhV2oPjfPwamg',
    appId: '1:687935619017:ios:0b8f8b77abad843d80f218',
    messagingSenderId: '687935619017',
    projectId: 'writing-learner-app',
    storageBucket: 'writing-learner-app.appspot.com',
    iosBundleId: 'com.example.writingLearner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFxn0YN57PQFHv5pcnmJqhV2oPjfPwamg',
    appId: '1:687935619017:ios:0b8f8b77abad843d80f218',
    messagingSenderId: '687935619017',
    projectId: 'writing-learner-app',
    storageBucket: 'writing-learner-app.appspot.com',
    iosBundleId: 'com.example.writingLearner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVywqCqXb8pdR5qDs9wIZvKSPoYgR873Y',
    appId: '1:687935619017:web:b235fbd51df33f7f80f218',
    messagingSenderId: '687935619017',
    projectId: 'writing-learner-app',
    authDomain: 'writing-learner-app.firebaseapp.com',
    storageBucket: 'writing-learner-app.appspot.com',
  );

}